devices:
    - device:
        alias: linux1
        ip: 192.168.50.6
        bsp: qemu
        connect:
            alias: ssh0
            type: ssh
            hostname: 192.168.50.6
            port: 22
            username: abcd
            password: abcd
    - device:
        alias: linux2
        ip: 192.168.50.6
        bsp: qemu
        connect:
            type: ssh
            hostname: 192.168.50.6
            port: 22
            username: abcd
            password: abcd